version: '3'

services:
  app:
    image: crockery:latest
    command: python manage.py runserver 0.0.0.0:8666
    restart: unless-stopped
    volumes:
      - .:/src
    ports:
      - "8666:8666"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=root
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=crock
      - DJANGO_SETTINGS_MODULE=crockery.settings.default
      - ENVIRONMENT=dev
      - APP_NAME=crockery
      - APP_VERSION=dev
      - APP_VERSION=0.1

  db:
    image: postgres:14-alpine
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
