version: '3'

services:
  app:
    image: crockery:latest
    platform: linux/amd64
    command: /src/manage.py runserver 0.0.0.0:8666
    restart: unless-stopped
    volumes:
      - ./src:/src
    ports:
      - "8666:8666"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=crockery.settings.default

  db:
    image: postgres:14-alpine
    platform: linux/amd64
    restart: unless-stopped
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:

