# Generated by Django 3.2.14 on 2022-07-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='alt_answer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
